services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spring-hydra
    ports:
      - 6500:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data: